development:
  adapter: mysql2
  encoding: utf8
  database: lunch_wheel
  username: 'root'#<%= ENV['DB_USERNAME'] %>
  password: 'root'#<%= ENV['DB_PASSWORD'] %>
  host: 127.0.0.1
  port: 3306

staging:
  adapter: mysql2
  encoding: utf8
  database: lunch_wheel
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: lunch_wheel
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 3306
